export const Languages: { label: string; code : string, active: boolean }[] = [
    { label: 'English (US)', code: 'en', active: true },
    { label: 'French (FR)', code: 'fr', active: true },
    { label: 'Spanish (ES)', code: 'es', active: false },
    { label: 'German (DE)', code: 'de', active: false },
    { label: 'Italian (IT)', code: 'it', active: false },
    { label: 'Chinese (ZH)', code: 'zh', active: false },
    { label: 'Japanese (JA)', code: 'ja', active: false },
    { label: 'Korean (KO)', code: 'ko', active: false },
    { label: 'Portuguese (PT)', code: 'pt', active: false },
    { label: 'Russian (RU)', code: 'ru', active: false },
    { label: 'Arabic (AR)', code: 'ar', active: false },
    { label: 'Hindi (HI)', code: 'hi', active: false },
    { label: 'Dutch (NL)', code: 'nl', active: false },
    { label: 'Swedish (SV)', code: 'sv', active: false },
    { label: 'Turkish (TR)', code: 'tr', active: false },
    { label: 'Greek (EL)', code: 'el', active: false },
    { label: 'Polish (PL)', code: 'pl', active: false },
    { label: 'Thai (TH)', code: 'th', active: false },
    { label: 'Vietnamese (VI)', code: 'vi', active: false },
    { label: 'Hebrew (HE)', code: 'he', active: false },
    { label: 'Norwegian (NO)', code: 'no', active: false },
    { label: 'Danish (DA)', code: 'da', active: false },
    { label: 'Finnish (FI)', code: 'fi', active: false },
    { label: 'Czech (CS)', code: 'cs', active: false },
    { label: 'Hungarian (HU)', code: 'hu', active: false },
    { label: 'Indonesian (ID)', code: 'id', active: false }
];